### PR TITLE
Feature/performance audit

### PR DESCRIPTION
**Pull request by ClaudiaRojasSoto**
# Description:
In this pull request, we present the improvements made in the feature/performance-audit branch. We worked as a team to identify and resolve performance issues in our database queries. Below are the details of the changes made and the results obtained.

## Changes Made:
- [x] **Query Optimizatio**n: We identified three queries that took more than 1000 ms to execute. We used EXPLAIN ANALYZE to analyze the execution plan and find areas for improvement.
- [x] **Index Creation**: We implemented indexes on columns that were frequently queried. The indexes created include:
[x] CREATE INDEX idx_animal_id ON visits (animal_id);
[x] CREATE INDEX idx_vet_id ON visits (vet_id);
[x] CREATE INDEX idx_email ON owners (email);

## Results:
- [x] The query SELECT COUNT(*) FROM visits where animal_id = 4; was optimized.
- [x] The query SELECT * FROM visits where vet_id = 2; was optimized.
- [x] The query SELECT * FROM owners where email = 'owner_18327@mail.com'; was optimized.

## Screenshots:
Captura de pantalla 2023-08-21 a la(s) 11 23 49
Captura de pantalla 2023-08-21 a la(s) 11 24 05
Captura de pantalla 2023-08-21 a la(s) 11 25 52
Captura de pantalla 2023-08-21 a la(s) 11 27 51
Captura de pantalla 2023-08-21 a la(s) 11 31 16
Captura de pantalla 2023-08-21 a la(s) 11 34 00
Captura de pantalla 2023-08-21 a la(s) 11 35 25
Captura de pantalla 2023-08-21 a la(s) 11 50 54
Captura de pantalla 2023-08-21 a la(s) 11 56 19
Captura de pantalla 2023-08-21 a la(s) 12 02 20
Captura de pantalla 2023-08-21 a la(s) 12 06 11
Captura de pantalla 2023-08-21 a la(s) 12 10 20

## Conclusion:
We have met the project requirements, significantly improving the performance of our queries. The changes made are in line with best practices and have been thoroughly tested.

We request the review of this pull request for its incorporation into the develop branch.
Greetings from:
@ClaudiaRojasSoto 
@CesarHerr

### CODE REVIEW

**Review by iambenkis — COMMENTED** [review]
Hi @ClaudiaRojasSoto  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that  is a pair-programming project , you should make sure that everyone has contributed code to the project , Kindly manage that 

-[ **Note** ] The contribution should not be on the README file but on technical tasks 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ClaudiaRojasSoto** [comment]
@iambenkis Since it is a database, we thought it was enough to let you know who we are working on the project because the code in the schema and in the queries is minimal (the one corresponding to this project). But of course, obviously, we will modify that. Thank you.

**Review by ShadyShawkat — APPROVED** [review]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ClaudiaRojasSoto** [comment]
Thank you @ShadyShawkat.

**Comment by CesarHerr** [comment]
@ShadyShawkat  Thanks for your review!! :smile:

**Pull request merged**
